# Generated by Django 3.2.8 on 2021-10-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='progress',
            field=models.IntegerField(verbose_name='Progress Percentage'),
        ),
    ]
