# Generated by Django 3.2.8 on 2021-10-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0003_alter_ticket_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='progress',
            field=models.IntegerField(blank=True, null=True, verbose_name='Progress Percentage'),
        ),
    ]
