# Generated by Django 3.2.8 on 2021-10-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_alter_ticket_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Closed', 'Closed'), ('Ongoing', 'Ongoing'), ('Complete', 'Complete')], default='Pending', max_length=9),
        ),
    ]
