# Generated by Django 3.2.8 on 2021-10-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0005_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
